language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt test
deploy:
  skip_cleanup: true
  provider: script
  script: ./.travis/deploy.sh $TRAVIS_TAG
  on:
    condition: '"${TRAVIS_SCALA_VERSION}" == "2.11.8" && "${TRAVIS_JDK_VERSION}" == "oraclejdk8"' 
    tags: true
